version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-12345678}
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474/browser/"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - constructgraph-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # HTTP
      - "6334:6334"  # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - constructgraph-network

  api:
    build: .
    image: constructgraph-api:dev
    command: ["python", "-m", "flask", "--app", "src.server.app", "run", "--host=0.0.0.0", "--port=5050", "--reload", "--debug"]
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-12345678}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=${QDRANT_COLLECTION:-construct_definitions}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POLL_INTERVAL=${POLL_INTERVAL:-5}
      - MAX_CONCURRENT_PDFS=${MAX_CONCURRENT_PDFS:-4}
      - RESET_DATABASE=true
    depends_on:
      - neo4j
      - qdrant
    ports:
      - "5050:5050"
    volumes:
      - ./src:/app/src:rw  # 实时同步源代码
      - ./data/input:/app/data/input:ro  # 只读输入目录
      - hf_cache:/root/.cache/huggingface
    stdin_open: true
    tty: true
    networks:
      - constructgraph-network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  qdrant_data:
  hf_cache:

networks:
  constructgraph-network:
    driver: bridge
